apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: blog-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
   DATA_SOURCE_NAME: exporter:apppassword@tcp(mysql:3306)/
