apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-project

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0
    helm:
      values: |
        prometheus:
          prometheusSpec:
            nodeSelector:
              role: platform
            tolerations:
              - key: platform
                operator: Equal
                value: "true"
                effect: NoSchedule

        grafana:
          nodeSelector:
            role: platform
          tolerations:
            - key: platform
              operator: Equal
              value: "true"
              effect: NoSchedule

        alertmanager:
          alertmanagerSpec:
            nodeSelector:
              role: platform
            tolerations:
              - key: platform
                operator: Equal
                value: "true"
                effect: NoSchedule

        kube-state-metrics:
          nodeSelector:
            role: platform
          tolerations:
            - key: platform
              operator: Equal
              value: "true"
              effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true
