apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: platform-project

  source:
    repoURL: https://github.com/nginx/nginx-gateway-fabric
    targetRevision: v1.6.1
    path: deploy/nodeport

    directory:
      recurse: true

    kustomize:
      patches:
        - target:
            kind: Deployment
            name: nginx-gateway
          patch: |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx-gateway
            spec:
              template:
                spec:
                  nodeSelector:
                    role: platform
                  tolerations:
                    - key: "platform"
                      operator: "Equal"
                      value: "true"
                      effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
