apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: platform-project

  source:
    repoURL: https://github.com/nginx/nginx-gateway-fabric
    targetRevision: v1.6.1
    path: deploy/nodeport

    kustomize:
      patches:
        - target:
            kind: Deployment
            name: nginx-gateway
          patch: |
            - op: add
              path: /spec/template/spec/nodeSelector
              value:
                role: platform
            - op: add
              path: /spec/template/spec/tolerations
              value:
                - key: "platform"
                  operator: "Equal"
                  value: "true"
                  effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
