apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: platform-project

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.0
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true

        server:
          enabled: true
          logLevel: "info"
          updateStrategyType: RollingUpdate

          nodeSelector:
            role: platform

          tolerations:
            - key: platform
              operator: Equal
              value: "true"
              effect: NoSchedule

          ha:
            enabled: true
            replicas: 2

            raft:
              enabled: true
              setNodeId: true

              config: |
                ui = true
                cluster_name = "vault-raft-cluster"
                disable_mlock = true

                listener "tcp" {
                  address         = "0.0.0.0:8200"
                  cluster_address = "0.0.0.0:8201"
                  tls_disable     = 1
                }

                seal "awskms" {
                  region     = "ap-south-1"
                  kms_key_id = "arn:aws:kms:ap-south-1:041875151232:key/1ea61afa-057f-4cbf-a498-0da74c74ada9"
                }

                storage "raft" {
                  path = "/vault/data"

                  retry_join {
                    leader_api_addr = "http://vault-0.vault-internal:8200"
                  }

                  retry_join {
                    leader_api_addr = "http://vault-1.vault-internal:8200"
                  }

                  retry_join {
                    leader_api_addr = "http://vault-2.vault-internal:8200"
                  }
                }

                service_registration "kubernetes" {}

          serviceAccount:
            create: false
            name: vault-sa

          dataStorage:
            enabled: true
            storageClass: vault-storage
            accessMode: ReadWriteOnce
            size: 1Gi

        ui:
          enabled: true
          serviceType: LoadBalancer

          nodeSelector:
            role: platform

          tolerations:
            - key: platform
              operator: Equal
              value: "true"
              effect: NoSchedule

        injector:
          enabled: true
          nodeSelector:
            role: platform
          tolerations:
            - key: platform
              operator: Equal
              value: "true"
              effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
