---
apiVersion: v1
kind: Service
metadata:
  name: app-green
  namespace: blog-prod
spec:
  selector:
    app: app-green
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: blog-prod
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: app-green

  template:
    metadata:
      labels:
        app: app-green
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "db-backend-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/db" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}"
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          export MYSQL_HOST="{{ .Data.data.MYSQL_HOST }}"
          export MYSQL_PORT="{{ .Data.data.MYSQL_PORT }}"
          {{- end }}

    spec:
      serviceAccountName: vault-app-green
      terminationGracePeriodSeconds: 30

      containers:
        - name: app
          image: charansait372/devops-blog-new:1.5
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false

          command: ["sh", "-c"]
          args:
            - source /vault/secret/db && exec java -jar /usr/src/app/app.jar

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 5
