nodeSelector:
  role: platform

tolerations:
  - key: platform
    operator: Equal
    value: "true"
    effect: NoSchedule

webhook:
  nodeSelector:
    role: platform

  tolerations:
    - key: platform
      operator: Equal
      value: "true"
      effect: NoSchedule

cainjector:
  nodeSelector:
    role: platform

  tolerations:
    - key: platform
      operator: Equal
      value: "true"
      effect: NoSchedule
