apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: blog-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "mysql-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/db"   # ✅ FIXED
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/db" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}"
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          {{- end }}
    spec:
      serviceAccountName: vault-mysql
      containers:
        - name: mysql
          image: mysql:8.0.36
          command: ["/bin/sh","-c"]
          args:
            - source /vault/secrets/db && exec docker-entrypoint.sh mysqld
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: mysql-sc
        resources:
          requests:
            storage: 2Gi
