apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-pdb
  namespace: blog-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # 👈 ADDED
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mysql

