apiVersion: v1
kind: Service
metadata:
  name: app-green
  namespace: default
  labels:
    monitoring: enabled # discoverable by ServiceMonitor
spec:
  selector:
    app: app-green
  ports:
    - name: http-metrics # ServiceMonitor to reference
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-green
  template:
    metadata:
      labels:
        app: app-green
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "db-backend-role"
        vault.hashicorp.com/agent-inject-secret-db: "secrets/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secrets/data/db" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}"
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          export MYSQL_HOST="{{ .Data.data.MYSQL_HOST }}"
          export MYSQL_PORT="{{ .Data.data.MYSQL_PORT }}"
          {{- end }}
    spec:
      serviceAccountName: vault-app-green
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z mysql 3306; do echo "waiting for mysql"; sleep 2; done
      containers:
        - name: app
          image: charansait372/devops-blog-new
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - source /vault/secrets/db && exec java -jar /usr/src/app/app.jar
          ports:
            - containerPort: 8080
