apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: green
  template:
    metadata:
      labels:
        app: app
        version: green
    spec:
      containers:
      - name: app
        image: charansait372/node-js:green
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER        # add this key to your secret if not present
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD    # add this key to your secret if not present
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_DATABASE
        ports:
        - containerPort: 5000
