apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: green
  template:
    metadata:
      labels:
        app: app
        version: green
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "db-backend-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/db" -}}
          export DB_USER="{{ .Data.data.MYSQL_USER }}"
          export DB_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export DB_NAME="{{ .Data.data.MYSQL_DATABASE }}"
          {{- end }}
        vault.hashicorp.com/addr: "http://vault-internal.vault.svc:8200"
    spec:
      serviceAccountName: vault-app-green
      containers:
        - name: app
          image: charansait372/node-js:green
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql-service"
          command: ["/bin/sh","-c"]
          args:
            - ". /vault/secrets/db && exec node /app/server.js"

---
apiVersion: v1
kind: Service
metadata:
  name: app-green
  namespace: default
spec:
  selector:
    app: app
    version: green
  ports:
    - port: 80
      targetPort: 5000

