apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "db-mysql-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/db" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}"
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-vault-addr: "http://vault-internal.vault.svc:8200"
    spec:
      serviceAccountName: vault-mysql
      containers:
        - name: mysql
          image: mysql:8.0
          command: ["/bin/sh", "-c"]
          args:
            - source /vault/secrets/db && exec docker-entrypoint.sh mysqld
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin","ping","-h","127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 5
