apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      name: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: blog-prod
spec:
  serviceName: "mysql-headless"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "mysql-role"
        vault.hashicorp.com/agent-inject-secret-db: "secrets/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secrets/data/db" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}"
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          export MYSQL_HOST="{{ .Data.data.MYSQL_HOST }}"
          export MYSQL_PORT="{{ .Data.data.MYSQL_PORT }}"
          {{- end }}
    spec:
      serviceAccountName: vault-mysql
      terminationGracePeriodSeconds: 60

      securityContext:
        fsGroup: 999

      containers:
        - name: mysql
          image: mysql:8.0.36
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsNonRoot: false   # MySQL official image requires root startup
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          command: ["/bin/sh", "-c"]
          args:
            - source /vault/secrets/db && exec docker-entrypoint.sh mysqld

          ports:
            - containerPort: 3306
              name: mysql

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"

          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5

          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql-sc
        resources:
          requests:
            storage: 5Gi

