apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bloggingapp-hpa
  namespace: default  # Specify the namespace if needed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bloggingapp-deployment
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Scale when CPU utilization exceeds 80%
