apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-green-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-green   # matches your backend deployment
  minReplicas: 2       # minimum number of pods
  maxReplicas: 5       # maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80   # scale when avg CPU > 80%
