apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Rewrite URL paths to the root
spec:
  ingressClassName: nginx
  rules:
  - host: .com  # Subdomain for backend access
    http:
      paths:
      - path: /  # Route for backend
        pathType: Prefix
        backend:
          service:
            name: bloggingapp-svc
            port:
              number: 80  # Port exposed by bloggingapp-svc
