apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bloggingapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Specifies NGINX as the ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /login  # Redirects all root (/) traffic to /login
spec:
  rules:
    - host: bloggingapp.example.com  # Replace with your domain or leave blank for default
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bloggingapp-svc
                port:
                  number: 80
