apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-network-policy
  labels:
    policy: local
spec:
  podSelector:
    matchLabels:
      app: mysql  # This applies the policy to MySQL pods
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: bloggingapp  # Only allows communication from bloggingapp pods
      ports:
        - protocol: TCP
          port: 3306  # MySQL default port
  policyTypes:
    - Ingress

