apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-claim
  labels:
    storage: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-standard  # This should match your PVC storage class
  hostPath:
    path: /mnt/data/mysql  # Local path on the node

  
