apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  labels:
    storage: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-standard

