apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_DATABASE: Ym9nZGI=          # blogdb
  MYSQL_USER: YXBwdXNlcg==           # appuser
  MYSQL_PASSWORD: eW91cnBhc3N3b3Jk  # yourpassword
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # rootpassword
