apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-standard  # Name of the StorageClass
provisioner: kubernetes.io/aws-ebs  # Provisioner for EBS volumes on AWS
parameters:
  type: gp2  # Type of volume: General Purpose SSD (you can use 'io1', 'st1', etc.)
  fsType: ext4  # Filesystem type to format the volume with (e.g., ext4, xfs)
  iopsPerGb: "10"  # Optional, defines IOPS (for io1 volumes)
reclaimPolicy: Retain  # Retain the volume after PVC is deleted (can also use Delete)
volumeBindingMode: Immediate  # Volume is bound immediately when PVC is created

