---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: blog-prod
  labels:
    app: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "mysql-exporter-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/db"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/db" -}}
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}"
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}"
          export MYSQL_HOST="{{ .Data.data.MYSQL_HOST }}"
          export MYSQL_PORT="{{ .Data.data.MYSQL_PORT }}"
          {{- end }}
    spec:
      serviceAccountName: vault-mysqld-exporter
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.15.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65534
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

          command: ["sh", "-c"]
          args:
            - >
              source /vault/secrets/db &&
              export DATA_SOURCE_NAME="$MYSQL_USER:$MYSQL_PASSWORD@($MYSQL_HOST:$MYSQL_PORT)/" &&
              exec /bin/mysqld_exporter

          ports:
            - containerPort: 9104
              name: metrics

          readinessProbe:
            httpGet:
              path: /metrics
              port: 9104
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9104
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: blog-prod
spec:
  selector:
    app: mysqld-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: app-green
  namespace: blog-prod
spec:
  selector:
    app: app-green
  ports:
    - port: 80
      targetPort: 8080
