apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-gateway
  namespace: argocd
spec:
  project: application-project

  source:
    repoURL: https://github.com/CharanSai8127/Fullstack-blogging
    targetRevision: main
    path: k8s/gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: blog-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
