apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-route
  namespace: blog-prod
spec:
  parentRefs:
    - name: app-gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - blogging-app.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: app-green
          port: 80
