apiVersion: v1
kind: ResourceQuota
metadata:
  name: blog-quota
  namespace: default
spec:
  hard:
    pods: "15"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    requests.storage: 20Gi
